name: Greeting

on: [pull_request_target]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Hello @${{ github.actor }}! Thank you for submitting a PR! We will try to review your PR as soon as possible and get back to you! Meanwhile you can browse the other AwesomeFoss repositories.
