name: Greet Contributors
on: 
  pull_request_target:

jobs:
  PR-Greeting:
    name: Greet Contributors
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: Greetings
          message: |
            Hello world ! :wave:
